ALTER TABLE tickets ADD COLUMN IF NOT EXISTS parent_id INTEGER REFERENCES tickets(id);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS owner TEXT;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'open'
  CHECK(status IN ('open','blocked','done'));
